config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#index"
  
  resources :sessions, only: [:create, :destroy]
  resources :incoming_messages, only: [:index, :show, :destroy]
  
  # 1.Initialization
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  # 2.Callback
  match '/auth/google_oauth2/callback', :to => 'sessions#create', via: [:get, :post]
  
  # "refresh emails" button
  match '/incoming_messages/refresh_emails', :to => 'incoming_messages#refresh_emails', via: [:post]

  get '/login', :to => 'sessions#new', :as => :login 
  get '/signout', :to => 'sessions#destroy', :as => :signout 
  get 'auth/failure', to: redirect('/')
 
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <h4><p>&copy; <%= t("un.footer_description")%></p></h4>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><%= t("un.title")%></a>
    </div>
        <div class='btn-toolbar pull-right'>
          <% if current_user %>
            <button class="btn btn-default RbtnMargin " type="button"><span class="glyphicon glyphicon-user"></span>
              <%= link_to "(#{ t("un.exit") + current_user.email})", signout_path, id: "sign_out" %>
            </button>
            <button class="btn btn-default RbtnMargin " type="button"><span class="	glyphicon glyphicon-envelope"></span>
               <%= link_to "#{ t("un.refresh_emails") }", incoming_messages_refresh_emails_path, method: :post %>
            </button>
    		  <% else %>
    	      <button class="btn btn-default RbtnMargin " type="button"><span class="glyphicon glyphicon-globe"></span>
    	        <%= link_to "#{ t("un.login") }", user_omniauth_authorize_path(:google_oauth2) %>
    	      </button>
    		  <% end %>
            <button class="btn btn-default dropdown-toggle RbtnMargin" type="button" data-toggle="dropdown"><%= t("un.language")%>
            <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li><%= link_to_unless_current "English", locale: "en" %></li>
              <li><%= link_to_unless_current "Русский", locale: "ru" %></li>
            </ul>
        </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-info"><%=message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %> 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("un.title")%></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <div class="container">
        <%= render 'layouts/messages' %>
          <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
  </body>
</html>